# Docker Compose has no built-in scheduler: these services define how to run
# the jobs in a container, not when. Scheduling lives in launchd on the host
# (see ops/install-launchd.sh and docs/operations-reliability.md).
services:
  train-job:
    build: .
    command: python -m pipeline.cli train
    deploy:
      restart_policy:
        condition: on-failure

  predict-job:
    build: .
    command: python -m pipeline.cli predict
    deploy:
      restart_policy:
        condition: on-failure
