# Docker Compose has no built-in scheduler: these services define how to run
# the jobs in a container, not when. Scheduling lives in GitHub Actions
# (see .github/workflows/ and docs/operations-reliability.md section 6).
services:
  train-job:
    build: .
    command: python -m pipeline.cli train
    deploy:
      restart_policy:
        condition: on-failure

  predict-job:
    build: .
    command: python -m pipeline.cli predict
    deploy:
      restart_policy:
        condition: on-failure
