---
title: "Footy Tipper Pipeline"
---

```{r}
prod_run = F
```

```{r, warning=FALSE, message=FALSE, include=FALSE}
library(here)
library(skimr)
library(Epi)
library(pROC)
library(googledrive)
library(scales)

drive_auth()

i_am("footy-tipper.Rmd")

helper_functions <- list.files(paste0(here(), "/R"), pattern = "*.R$", 
                               full.names = TRUE, ignore.case = TRUE)

sapply(helper_functions, source, .GlobalEnv)
```

# Get and split the dataset

```{r, warning=FALSE, message=FALSE}
footy_tipping_data <- get_data(year_span = year_span) %>%
  clean_data() %>%
  fixture_result(pipeline = pipeline) %>%
  feature_engineering(form_period = form_period, pipeline = pipeline) %>%
  elo_variables(carry_over = carry_over, k_val = k_val, elo_init = elo_init) %>%
  home_ground_advantage() %>%
  filter(competition_year != min(competition_year),
         !is.na(team_head_to_head_odds_away)) %>%
  group_by(game_state_name) %>%
  group_split()

train_df <- footy_tipping_data[[1]]

inference_df <- footy_tipping_data[[2]] %>%
  filter(round_id == min(round_id))

skim(train_df)
```

```{r, warning=FALSE, message=FALSE}
opt_predictors <- perform_rfe(data = train_df, k = 5, opt_metric, maximise = T, steps = NULL, outcome_var = outcome_var, predictors = predictors) 
```

```{r}
opt_predictors
```


# Train the model

```{r, warning=FALSE, message=FALSE}
cv <- train_multiclass_model(data = train_df, predictors = opt_predictors, outcome_var = outcome_var, opt_metric = opt_metric)

model <- cv$finalModel
outputs <- model_properties(model, train_df, inference_df, positive)
```

```{r}
outputs$confusion_matrix
```

```{r, warning=FALSE, message=FALSE}
outputs$importance
```

```{r}
outputs$round_performance
```

```{r}
outputs$benchmarking
```

```{r}
outputs$model_lift
```


# Predict the results for the round

```{r, warning=FALSE, message=FALSE}
predictions <- make_predicitons(inference_df, model, predictors, outcome_var)
predictions
```

# Save them to the drive

```{r}
save_predictions(predictions, inference_df, prod_run = prod_run)
```


# extra thangs...

```{r}
levons_picks(predictions, prod_run = prod_run)
```
