---
title: "R Notebook"
output: html_notebook
---



```{r}
library(here)
i_am("research/byes.Rmd")

helper_functions <- list.files(paste0(here(), "/R"), pattern = "*.R$", 
                               full.names = TRUE, ignore.case = TRUE)

sapply(helper_functions, source, .GlobalEnv)

footy_tipping_data <- get_data(year_span = year_span) %>%
  clean_data() %>%
  group_by(game_state_name) %>%
  group_split() %>% .[[1]]
```

```{r}
teams <- footy_tipping_data$team_home %>% unique()

home_teams <- footy_tipping_data %>%
  group_by(round_id, competition_year) %>%
  select(team_home) %>% rename(team = team_home) 

away_teams <- footy_tipping_data %>%
  group_by(round_id, competition_year) %>%
  select(team_away) %>% rename(team = team_away)

teams <- bind_rows(home_teams, away_teams) %>%
  group_by(round_id, competition_year) %>%
  mutate(bye_last_week = ifelse(team %in% lag(team), 0, 1))

thing <- footy_tipping_data %>%
  arrange(desc(game_id)) %>%
  group_by(team_home, competition_year, round_id) %>%
  #mutate(bye_last_week_home = ifelse((team_home %in% lag(team_home)) & (team_home %in% lead(team_away)), 1, 0)) %>%
  mutate(bye_last_week_home = ifelse(team_home %in% lag(team_home), 1, 0))

thing %>%
  select(game_id, round_id, competition_year, team_home, team_away, bye_last_week_home) %>% with(table(bye_last_week_home))
```















