---
title: "Creating new features"
output: html_notebook
---

```{r, warning=FALSE, message=TRUE}
library(here)
library(lubridate)
library(zoo)

i_am("research/creating-new-features.Rmd")

source(paste0(here(),"/R/get-data.R"))

footy_tipper_df <- get_data(year_span = 2012:2023) 
 
footy_tipper_df
```
# corona season

an easy one aimed at reducing bias from a weird season

```{r}
footy_tipper_df <- footy_tipper_df %>%
  mutate(corona_season = ifelse(competition_year == 2020, 1, 0))
```

# Seasonality Variables

```{r}
footy_tipper_df <- footy_tipper_df %>%
  mutate(start_hour = hour(start_time))
```

# Form variables

## seasonal vars
* home record (as a number)
* away record (as a number)
* season record (as a number)
* points for
* points against
* point diff

```{r}
home_games <- footy_tipper_df %>%
  select(game_id, competition_year, team_home, team_final_score_home, team_final_score_away, home_team_result) %>%
  rename(team = team_home, points_for = team_final_score_home, points_against = team_final_score_away) %>%
  arrange(game_id) 

home_record <- home_games %>%
  group_by(team, competition_year) %>%
  mutate(home_record =
           cumsum(case_when(
             home_team_result == 'Win'  ~ 1, 
             home_team_result == 'Loss' ~ -1,
             TRUE                       ~ 0)),
         home_points_for = cumsum(points_for),
         home_points_against = cumsum(points_against),
         home_points_diff = points_for - points_against) %>%
  mutate_at(vars(home_record, home_points_for, home_points_against, home_points_diff), lag) %>%
  replace(is.na(.), 0) %>%
  ungroup() %>%
  select(-c(competition_year, home_team_result, points_for, points_against, team))

away_games <- footy_tipper_df %>%
  select(game_id, competition_year, team_away, team_final_score_home, team_final_score_away, home_team_result) %>%
  rename(team = team_away, points_for = team_final_score_away, points_against = team_final_score_home) %>%
  arrange(game_id) 

away_record <- away_games %>%
  group_by(team, competition_year) %>%
  mutate(away_record =
           cumsum(case_when(
             home_team_result == 'Win'  ~ -1, 
             home_team_result == 'Loss' ~ 1,
             TRUE                       ~ 0)),
         away_points_for = cumsum(points_for),
         away_points_against = cumsum(points_against),
         away_points_diff = points_for - points_against) %>%
  mutate_at(vars(away_record, away_points_for, away_points_against, away_points_diff), lag) %>%
  replace(is.na(.), 0) %>%
  ungroup() %>%
  select(-c(competition_year, home_team_result, points_for, points_against, team))

season_record <- bind_rows(
  home_games %>% mutate(is_home_team = T), 
  away_games %>% mutate(is_home_team = F)
  ) %>%
  arrange(game_id) %>%
  group_by(team, competition_year) %>%
  mutate(season_record =
           cumsum(case_when(
             home_team_result == 'Win' & is_home_team == T  ~ 1, 
             home_team_result == 'Loss' & is_home_team == T ~ -1,
             home_team_result == 'Win' & is_home_team == F  ~ -1, 
             home_team_result == 'Loss' & is_home_team == F ~ 1,
             TRUE                       ~ 0)),
         season_points_for = cumsum(points_for),
         season_points_against = cumsum(points_against),
         season_points_diff = points_for - points_against) %>%
  mutate_at(vars(season_record, season_points_for, season_points_against, season_points_diff), lag) %>%
  replace(is.na(.), 0) %>%
  ungroup() %>%
  select(-c(competition_year, home_team_result, points_for, points_against, team)) %>%
  group_by(is_home_team) %>%
  group_split()

footy_tipper_df <- footy_tipper_df %>%
  left_join(season_record[[1]] %>% select(-is_home_team), by = "game_id") %>%
  left_join(season_record[[2]] %>% select(-is_home_team), by = "game_id", suffix = c("_away", "_home")) %>%
  left_join(home_record, by = "game_id") %>%
  left_join(away_record, by = "game_id", suffix = c("_home", "_away"))

footy_tipper_df
```


## form (last 5 games) vars
```{r}
home_games <- footy_tipper_df %>%
  select(game_id, competition_year, team_home, team_final_score_home, team_final_score_away, home_team_result) %>%
  rename(team = team_home, points_for = team_final_score_home, points_against = team_final_score_away) %>%
  arrange(game_id) 

away_games <- footy_tipper_df %>%
  select(game_id, competition_year, team_away, team_final_score_home, team_final_score_away, home_team_result) %>%
  rename(team = team_away, points_for = team_final_score_away, points_against = team_final_score_home) %>%
  arrange(game_id) 

season_form <- bind_rows(
  home_games %>% mutate(is_home_team = T), 
  away_games %>% mutate(is_home_team = F)
  ) %>%  
  arrange(game_id) %>%
  group_by(team, competition_year) %>%
  mutate(season_form = ifelse(seq(n()) < 5,
                              cumsum(case_when(
                                home_team_result == 'Win' & is_home_team == T  ~ 1, 
                                home_team_result == 'Loss' & is_home_team == T ~ -1,
                                home_team_result == 'Win' & is_home_team == F  ~ -1, 
                                home_team_result == 'Loss' & is_home_team == F ~ 1,
                                TRUE                       ~ 0)),
                               rollsum(case_when(
                                home_team_result == 'Win' & is_home_team == T  ~ 1, 
                                home_team_result == 'Loss' & is_home_team == T ~ -1,
                                home_team_result == 'Win' & is_home_team == F  ~ -1, 
                                home_team_result == 'Loss' & is_home_team == F ~ 1,
                                TRUE                       ~ 0), 5, align = "right", fill = 0)),
         season_points_for_form = ifelse(seq(n()) < 5,
                                         cumsum(points_for),
                                         rollapply(points_for, FUN = mean, width = 5, align = "right", fill = 0)),
         season_points_against_form = ifelse(seq(n()) < 5,
                                             cumsum(points_against),
                                             rollapply(points_against, FUN = mean, width = 5, align = "right", fill = 0)),
         season_diff_form = ifelse(seq(n()) < 5,
                                   cumsum(points_for - points_against),
                                   rollapply(points_for - points_against, FUN = mean, width = 5, align = "right", fill = 0))) %>%
  mutate_at(vars(season_form, season_points_for_form, season_points_against_form, season_diff_form), lag) %>% 
  replace(is.na(.), 0) %>%
  ungroup() %>%
  select(-c(competition_year, home_team_result, points_for, points_against, team)) %>%
  group_by(is_home_team) %>%
  group_split()

footy_tipper_df <- footy_tipper_df %>%
  left_join(season_form[[1]] %>% select(-is_home_team), by = "game_id") %>%
  left_join(season_form[[2]] %>% select(-is_home_team), by = "game_id", suffix = c("_away", "_home"))
```

## opponent vars

```{r}
matchups <- footy_tipper_df %>%
  filter(game_state_name == "Final") %>%
  with(table(team_home, team_away, home_team_result, game_id)) %>% as.data.frame() %>%
  mutate(form = Freq*case_when(
    home_team_result == 'Win'  ~ 1,
    home_team_result == 'Loss' ~ -1,
    TRUE                       ~ 0
  ),
  game_id = as.numeric(as.character(game_id))) %>%
  select(game_id, team_home, team_away, form)

thing <- footy_tipper_df %>% 
  left_join(matchups, by = c("game_id", "team_home", "team_away"))
```


```{r}
matchups <- footy_tipper_df %>%
  filter(game_state_name == "Final") %>%
  with(table(team_home, team_away, home_team_result, competition_year, round_id)) %>% as.data.frame() %>%
  mutate(form = Freq*case_when(
    home_team_result == 'Win'  ~ 1,
    home_team_result == 'Loss' ~ -1,
    TRUE                       ~ 0
  )) %>%
  select(-c(home_team_result, Freq)) %>%
  pivot_wider(names_from = team_home, values_from = form, values_fn = sum) %>%
  pivot_longer(cols = -c(competition_year, round_id), names_to = "team_home", values_to = "form")

matchups
```

```{r}
footy_tipper_df <- footy_tipper_df %>%
  group_by(team_home, team_away) %>%
  mutate(form = case_when(
    home_team_result == 'Win'  ~ 1,
    home_team_result == 'Loss' ~ -1,
    TRUE                       ~ 0
  ),
  matchup_form = ifelse(seq(n()) < 5,
                   cumsum(form),
                   rollsum(form, 5, align = "right", fill = 0)) %>% lag() %>% replace_na(0))

footy_tipper_df
```





































