---
title: "Data Preparation"
---

```{r, warning=FALSE, message=FALSE, include=FALSE}
i_am("pipeline/data-prep/data-prep.Rmd")

# find and load all the helper functions for the project
data_prep_functions <- list.files(paste0(here(), "/pipeline/data-prep"), pattern = "*.R$",
                                  full.names = TRUE, ignore.case = TRUE)

sapply(data_prep_functions, source, .GlobalEnv)
```

```{r, warning=FALSE, message=FALSE}
footy_tipping_data <- data_pipeline(year_span, pipeline = 'binomial', form_period, carry_over, k_val, elo_init)

train_df <- footy_tipping_data$train_df
inference_df <- footy_tipping_data$inference_df

skim(train_df)
```

```{r, warning=FALSE, message=FALSE}
# Connect to the SQLite database
con <- dbConnect(SQLite(), paste0(here(), "/data/footy-tipper-db.sqlite"))

# Write your dataframes
dbWriteTable(con, "train_df", train_df, overwrite = T)
dbWriteTable(con, "inference_df", inference_df, overwrite = T)

# Disconnect from the SQLite database
dbDisconnect(con)
```
