---
title: "Footy Tipper Pipeline"
output: html_notebook
---

```{r, warning=FALSE, message=FALSE}
library(here)
library(skimr)
library(Epi)
library(pROC)

i_am("pipeline/footy-tipper.Rmd")

source(paste0(here(),"/R/get-data.R"))
source(paste0(here(),"/R/feature-engineering.R"))
source(paste0(here(),"/R/modelling-functions.R"))
```

# Get and split the dataset

```{r, warning=FALSE, message=FALSE}
footy_tipping_data <- get_data(year_span = 2012:2023) %>%
  feature_engineering(form_period = 5, pipeline = 'binomial') %>%
  group_by(game_state_name) %>%
  group_split()

train_df <- footy_tipping_data[[1]]

inference_df <- footy_tipping_data[[2]] %>%
  filter(round_id == min(round_id))

skim(train_df)
```

# Train the model

```{r, warning=FALSE, message=FALSE}
predictors <- c("round_id", "round_name", "game_number", "venue_name", "team_home", "team_position_home", "team_away", "team_position_away", "competition_year", "corona_season", "start_hour", "season_record_away", "season_points_for_away", "season_points_against_away", "season_points_diff_away", "season_record_home",  "season_points_for_home", "season_points_against_home","season_points_diff_home", "season_form_away", "season_points_for_form_away", "season_points_against_form_away", "season_diff_form_away", "season_form_home", "season_points_for_form_home", "season_points_against_form_home", "season_diff_form_home", "matchup_form", "position_diff")

model <- train_model(data = train_df, 
                     predictors = predictors,
                     outcome_var = "home_team_result")

cut_optimised_model <- rf_cutoff_select(model)
model <- cut_optimised_model$rf_model
```

```{r, warning=FALSE, message=FALSE}
roc(train_df$home_team_result, model$votes[,"Win"]) %>% 
  plot(main = 'Model ROC curve')
```

```{r, warning=FALSE, message=FALSE}
# new vals
train_df <- train_df %>%
  mutate(prediction = as.factor(ifelse(model$votes[,"Win"] > cut_optimised_model$cutoff[2], "Win", "Loss")))

# print confusion matrix statistics
cm <- train_df %>% 
  with(table(train_df$home_team_result, train_df$prediction))

confusionMatrix(cm, positive = "Win")
```


```{r, warning=FALSE, message=FALSE}
importance(model) %>% t() %>% .[1,] %>% 
  as.tibble(rownames = "variable") %>%
  arrange(desc(value)) %>%
  ggplot(aes(x = variable, y = value, fill = variable)) +
  geom_bar(stat = "identity") +
    coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Importance of variables",
       x = NULL, y = "Importance")
```

# Predict the results for the round

```{r, warning=FALSE, message=FALSE}
predictions <- data.frame(
  game_id = inference_df$game_id,
  team_home = inference_df$team_home,
  team_away = inference_df$team_away,
  home_team_result = predict(model, inference_df %>% select(all_of(c(predictors, "home_team_result"))))
)

predictions
```

# Save them to the drive

```{r}
write_csv(predictions, paste0(here(), "/data/predictions/round", unique(inference_df$round_id), "_", unique(inference_df$competition_year), ".csv"))
```



