---
title: "Multiclass Footy Tipper Pipeline"
output: html_notebook
---

```{r, warning=FALSE, message=FALSE}
library(here)
library(skimr)
library(Epi)
library(pROC)
library(googledrive)
library(googlesheets4)

i_am("pipeline/multiclass-footy-tipper.Rmd")

drive_auth()

source(paste0(here(),"/R/get-data.R"))
source(paste0(here(),"/R/clean-data.R"))
source(paste0(here(),"/R/feature-engineering.R"))
source(paste0(here(),"/R/modelling-functions.R"))
source(paste0(here(),"/R/config.R"))
```

# Get and split the dataset

```{r, warning=FALSE, message=FALSE}
footy_tipping_data <- get_data(year_span = 2012:2023) %>%
  clean_data() %>%
  feature_engineering(form_period = 5, pipeline = 'multiclass') %>%
  elo_variables() %>%
  filter(competition_year != min(competition_year)) %>%
  group_by(game_state_name) %>%
  group_split()

train_df <- footy_tipping_data[[1]]

inference_df <- footy_tipping_data[[2]] %>%
  filter(round_id == min(round_id))

skim(train_df)
```

# Train the model

```{r, warning=FALSE, message=FALSE}
cv <- train_multiclass_model(data = train_df, 
                     predictors = predictors,
                     outcome_var = "home_team_result",
                     metric = "Kappa")

model <- cv$finalModel
```

```{r}
model$confusion[-1,2:3] %>% confusionMatrix(positive = "Win")
```

```{r, warning=FALSE, message=FALSE}
importance(model) %>% t() %>% .[1,] %>% 
  as.tibble(rownames = "variable") %>%
  arrange(desc(value)) %>%
  ggplot(aes(x = variable, y = value, fill = variable)) +
  geom_bar(stat = "identity") +
    coord_flip() +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(title = "Importance of variables",
       x = NULL, y = "Importance")
```

# Predict the results for the round

```{r, warning=FALSE, message=FALSE}
predictions <- data.frame(
  game_id = inference_df$game_id,
  team_home = inference_df$team_home,
  team_away = inference_df$team_away,
  home_team_result = predict(model, inference_df %>% select(all_of(c(predictors, "home_team_result")))),
  home_team_win_prob = predict(model, inference_df %>% select(all_of(c(predictors, "home_team_result"))), type = "prob")[,"Win"],
  home_team_draw_prob = predict(model, inference_df %>% select(all_of(c(predictors, "home_team_result"))), type = "prob")[,"Draw"],
  home_team_lose_prob = predict(model, inference_df %>% select(all_of(c(predictors, "home_team_result"))), type = "prob")[,"Loss"],
  home_elo = inference_df$home_elo,
  away_elo = inference_df$away_elo
)

predictions
```

# Save them to the drive

```{r}
prob <- model$votes %>% as.data.frame %>% mutate(response = model$y)
prob

bet_span <- seq(1.05, 2, 0.05)

for (m in length(bet_span)){
  
  win_cut <- optimal.cutpoints(X = "Win", status = "response", 
                    tag.healthy = "Loss", methods = "MaxKappa",
                    CFN = 3, CFP = bet_span[10] - 1, data = prob)$MaxKappa$Global$optimal.cutoff$cutoff
  
}

optimal.cutpoints(X = "Win", status = "response", 
                  tag.healthy = "Loss", methods = "MaxKappa", 
                  control = control.cutpoints(CFN = 6, CFP = 20), data = prob)


```


```{r}
# Create an empty spreadsheet. It is stored as an object with a sheet_id and drive_id 
ss <- gs4_create(name = paste0("r", unique(inference_df$round_id), "_", unique(inference_df$competition_year), ".csv"), sheets = "Sheet 1")

# Put the data.frame in the spreadsheet and provide the sheet_id so it can be found
sheet_write(data = predictions, ss = ss, sheet ="Sheet 1")

# Move your spreadsheet to the desired location
drive_mv(file = ss, path = "footy-tipping-predictions/", overwrite = T)
```


```{r}
file_name = paste0("round", unique(inference_df$round_id), "_", unique(inference_df$competition_year), ".csv")

write.csv(x = predictions, file = file_name)

drive_upload(media = file_name, path = "footy-tipping-predictions/", overwrite = T)
```



