"""Club Context: evidence-gated psychosocial match context in shadow mode."""

from .attention import (
    GDELT_COVERAGE_START_YEAR,
    AttentionIndex,
    backfill_attention,
    load_attention_index,
)
from .features import (
    CONTEXT_FEATURE_COLUMNS,
    ORIENTATION_COLUMNS,
    build_context_match_features,
    fill_context_feature_columns,
    resolve_context_for_matches,
)
from .materiality import (
    OFFSET_SPECIFICATIONS,
    evaluate_context_offset,
    evaluate_form_shortfall,
)
from .registry import (
    ArticleSnapshot,
    ContextEvent,
    EventEntity,
    EventSource,
    RegistryValidationReport,
    canonicalize_url,
    event_is_eligible,
    finish_ingestion_run,
    insert_context_event,
    load_eligible_events,
    safe_insert_context_event,
    safe_upsert_article_snapshot,
    set_event_review_status,
    start_ingestion_run,
    upsert_article_snapshot,
    validate_registry,
)
from .schema import (
    CONTEXT_FEATURE_VERSION,
    CONTEXT_SCHEMA_VERSION,
    context_schema_current,
    context_tables_present,
    ensure_context_tables,
)
from .snapshots import create_prediction_context_snapshot, load_prediction_context
from .sources import (
    DiscoveryAdapter,
    DiscoveryCandidate,
    SourcePolicy,
    adapter_can_run,
)
from .taxonomy import (
    CONTEXT_TAXONOMY_VERSION,
    DISRUPTIVE_CATEGORIES,
    MIN_ELIGIBLE_CONFIDENCE,
    AcquisitionMethod,
    ConfirmationStatus,
    EntityRelationship,
    EntityType,
    EventCategory,
    EventDisposition,
    EventPhase,
    EvidenceRole,
    IngestionMode,
    IngestionStatus,
    KnownAtBasis,
    PredictionMode,
    ReviewStatus,
    RightsStatus,
    Sensitivity,
    SourceClass,
)
from .time import (
    capture_live_decision_at_utc,
    parse_datetime,
    round_target_at_utc,
    round_target_map,
    utc_iso,
)

# Explicit long-form alias for callers that merge several context families.
build_club_context_match_features = build_context_match_features

__all__ = [
    "CONTEXT_FEATURE_COLUMNS",
    "GDELT_COVERAGE_START_YEAR",
    "OFFSET_SPECIFICATIONS",
    "ORIENTATION_COLUMNS",
    "AttentionIndex",
    "CONTEXT_FEATURE_VERSION",
    "CONTEXT_SCHEMA_VERSION",
    "CONTEXT_TAXONOMY_VERSION",
    "MIN_ELIGIBLE_CONFIDENCE",
    "AcquisitionMethod",
    "ArticleSnapshot",
    "ConfirmationStatus",
    "ContextEvent",
    "DiscoveryAdapter",
    "DiscoveryCandidate",
    "EntityRelationship",
    "EntityType",
    "DISRUPTIVE_CATEGORIES",
    "EventCategory",
    "EventDisposition",
    "EventEntity",
    "EventPhase",
    "EventSource",
    "EvidenceRole",
    "IngestionMode",
    "IngestionStatus",
    "KnownAtBasis",
    "PredictionMode",
    "RegistryValidationReport",
    "ReviewStatus",
    "RightsStatus",
    "Sensitivity",
    "SourceClass",
    "SourcePolicy",
    "adapter_can_run",
    "backfill_attention",
    "build_club_context_match_features",
    "build_context_match_features",
    "canonicalize_url",
    "capture_live_decision_at_utc",
    "context_tables_present",
    "context_schema_current",
    "create_prediction_context_snapshot",
    "ensure_context_tables",
    "evaluate_context_offset",
    "evaluate_form_shortfall",
    "event_is_eligible",
    "fill_context_feature_columns",
    "finish_ingestion_run",
    "insert_context_event",
    "load_attention_index",
    "load_eligible_events",
    "load_prediction_context",
    "parse_datetime",
    "resolve_context_for_matches",
    "round_target_at_utc",
    "round_target_map",
    "safe_insert_context_event",
    "safe_upsert_article_snapshot",
    "set_event_review_status",
    "start_ingestion_run",
    "upsert_article_snapshot",
    "utc_iso",
    "validate_registry",
]
