# training params
opt_metric = "accuracy" # ROC, F1 or accuracy
num_folds = 5
use_rfe = True

# outcome variable
outcome_var = "home_team_result"
positive = "Win"

# predictors
predictors = [
    "round_id"
    , "round_name"
    , "game_number"
    , "venue_name"
    , "city"
    , "team_home"
    , "punt_odds_diff"
    , "line_amount_diff"
    , "recent_form_diff"
    , "team_away"
    , "competition_year"
    , "broadcast_channel1"
    , "broadcast_channel2"
    , "broadcast_channel3"
    , "recent_form_home"
    , "players_used_diff"
    , "average_winning_margin_diff"
    , "average_losing_margin_diff"
    , "win_rate_diff"
    , "loss_rate_diff"
    , "draw_rate_diff"
    , "competition_point_rate_diff"
    , "avg_points_for_diff"
    , "avg_points_against_diff"
    , "avg_points_difference_diff"
    , "home_win_rate_home"         
    , "home_draw_rate_home"
    , "home_loss_rate_home"
    , "away_win_rate_home"         
    , "away_loss_rate_home"
    , "avg_tries_for_home"
    , "avg_tries_conceded_home"    
    , "avg_goals_for_home"
    , "avg_goals_conceded_home"      
    , "position_diff"
    , "start_hour"
    , "game_day"                   
    , "matchup_form"    
    , "elo_diff"           
    , "elo_prob_diff"
    , "elo_draw_prob"
    , "state_of_origin"
    , "home_ground_advantage"
    , "turn_around_diff"
]