# training params
opt_metric = "accuracy" # ROC, F1 or accuracy
num_folds = 5
use_rfe = True

# outcome variable
outcome_var = "home_team_result"
positive = "Win"

# predictors
predictors = [
    "round_id"
    , "round_name"
    , "game_number"
    , "venue_name"
    , "city"
    , "team_home"
    , "punt_odds_diff"
    , "line_amount_diff"
    , "recent_form_diff"
    # , "team_head_to_head_odds_home" 
    # , "team_line_odds_home" 
    # , "team_line_amount_home"
    # , "position_home"
    , "team_away"
    # , "position_away"
    # , "team_head_to_head_odds_away" 
    # , "team_line_odds_away"
    # , "team_line_amount_away"
    , "competition_year"
    , "broadcast_channel1"
    , "broadcast_channel2"
    , "broadcast_channel3"
    # , "wins_home"                  
    # , "draws_home"                  
    # , "losses_home"
    # , "byes_home"                  
    # , "competition_points_home"
    # , "points_for_home"             
    # , "points_against_home"        
    # , "points_difference_home"
    # , "home_wins_home"
    # , "home_draws_home"            
    # , "home_losses_home"
    # , "away_wins_home"
    # , "away_draws_home"            
    # , "away_losses_home"
    , "recent_form_home"
    # , "season_form_home"
    # , "tries_for_home"
    # , "tries_conceded_home"
    # , "goals_for_home"             
    # , "goals_conceded_home"
    # , "field_goals_for_home"
    # , "field_goals_conceded_home"  
    # , "players_used_home"
    , "players_used_diff"
    # , "average_winning_margin_home"
    # , "average_losing_margin_home" 
    , "average_winning_margin_diff"
    , "average_losing_margin_diff" 
    # , "close_games_home"
    # , "win_rate_home"
    # , "draw_rate_home"             
    # , "loss_rate_home"
    , "win_rate_diff"
    , "loss_rate_diff"
    , "draw_rate_diff"
    # , "competition_point_rate_home"
    , "competition_point_rate_diff"

    # , "avg_points_for_home"    
    # , "avg_points_against_home"
    # , "avg_points_difference_home"
    , "avg_points_for_diff"
    , "avg_points_against_diff"
    , "avg_points_difference_diff"


    , "home_win_rate_home"         
    , "home_draw_rate_home"
    , "home_loss_rate_home"
    , "away_win_rate_home"         
    , "away_loss_rate_home"


    , "avg_tries_for_home"
    , "avg_tries_conceded_home"    
    , "avg_goals_for_home"
    , "avg_goals_conceded_home"
    # , "close_game_rate_home"     
    # , "wins_away"
    # , "draws_away"
    # , "losses_away"                
    # , "byes_away"
    # , "competition_points_away"
    # , "points_for_away"            
    # , "points_against_away"
    # , "points_difference_away"
    # , "home_wins_away"             
    # , "home_draws_away"
    # , "home_losses_away"
    # , "away_wins_away"             
    # , "away_draws_away"
    # , "away_losses_away"
    # , "recent_form_away"           
    # , "season_form_away"
    # , "tries_for_away"
    # , "tries_conceded_away"        
    # , "goals_for_away"
    # , "goals_conceded_away"
    # , "field_goals_for_away"       
    # , "field_goals_conceded_away"
    # , "players_used_away"
    # , "average_winning_margin_away"
    # , "average_losing_margin_away"
    # , "close_games_away"
    # , "win_rate_away"              
    # , "draw_rate_away"
    # , "loss_rate_away"
    # , "competition_point_rate_away"
    # , "avg_points_for_away"
    # , "avg_points_against_away"
    # , "avg_points_difference_away" 
    # , "home_win_rate_away"
    # , "home_draw_rate_away"
    # , "home_loss_rate_away"        
    # , "away_win_rate_away"
    # , "away_loss_rate_away"
    # , "avg_tries_for_away"         
    # , "avg_tries_conceded_away"
    # , "avg_goals_for_away"
    # , "avg_goals_conceded_away"    
    # , "close_game_rate_away"        
    , "position_diff"
    , "start_hour"
    , "game_day"                   
    , "matchup_form"
    # , "home_elo"
    # , "away_elo"     
    , "elo_diff"              
    # , "home_elo_prob"
    # , "away_elo_prob"
    , "elo_prob_diff"
    , "elo_draw_prob"
    , "state_of_origin"
    , "home_ground_advantage"
    # , "turn_around_home"
    # , "turn_around_away"
    , "turn_around_diff"
]