INSERT INTO prediction_explanations (
    game_id,
    schema_version,
    taxonomy_version,
    generated_at,
    model_release,
    why_line,
    prob_route,
    attribution_source,
    guard_fired,
    reconciled,
    line_applied,
    total_applied,
    published_cond,
    tier_a_prob,
    tier_b_prob,
    tier_c_prob,
    market_prob,
    pooled_logit,
    temperature,
    feature_multiplier,
    mu_model_home,
    mu_model_away,
    mu_baseline_home,
    mu_baseline_away,
    mu_blended_home,
    mu_blended_away,
    mu_final_home,
    mu_final_away,
    tier_a_attack_home,
    tier_a_defence_home,
    tier_a_attack_away,
    tier_a_defence_away,
    prob_drivers_json,
    margin_drivers_json,
    family_prob_json,
    family_margin_json,
    trace_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(game_id) DO UPDATE SET
    schema_version = excluded.schema_version,
    taxonomy_version = excluded.taxonomy_version,
    generated_at = excluded.generated_at,
    model_release = excluded.model_release,
    why_line = excluded.why_line,
    prob_route = excluded.prob_route,
    attribution_source = excluded.attribution_source,
    guard_fired = excluded.guard_fired,
    reconciled = excluded.reconciled,
    line_applied = excluded.line_applied,
    total_applied = excluded.total_applied,
    published_cond = excluded.published_cond,
    tier_a_prob = excluded.tier_a_prob,
    tier_b_prob = excluded.tier_b_prob,
    tier_c_prob = excluded.tier_c_prob,
    market_prob = excluded.market_prob,
    pooled_logit = excluded.pooled_logit,
    temperature = excluded.temperature,
    feature_multiplier = excluded.feature_multiplier,
    mu_model_home = excluded.mu_model_home,
    mu_model_away = excluded.mu_model_away,
    mu_baseline_home = excluded.mu_baseline_home,
    mu_baseline_away = excluded.mu_baseline_away,
    mu_blended_home = excluded.mu_blended_home,
    mu_blended_away = excluded.mu_blended_away,
    mu_final_home = excluded.mu_final_home,
    mu_final_away = excluded.mu_final_away,
    tier_a_attack_home = excluded.tier_a_attack_home,
    tier_a_defence_home = excluded.tier_a_defence_home,
    tier_a_attack_away = excluded.tier_a_attack_away,
    tier_a_defence_away = excluded.tier_a_defence_away,
    prob_drivers_json = excluded.prob_drivers_json,
    margin_drivers_json = excluded.margin_drivers_json,
    family_prob_json = excluded.family_prob_json,
    family_margin_json = excluded.family_margin_json,
    trace_json = excluded.trace_json
