---
title: "Get, Save and Use Predicitons"
output: github_document
---

# Get the predicitons from the DB and save them in the Google Drive

```{r, warning=FALSE, message=FALSE, include=FALSE}
i_am("pipeline/use-predictions/use-predictions.Rmd")

# find and load all the helper functions for the project
save_predicitons_functions <- list.files(
    paste0(here(), "/pipeline/use-predictions"), pattern = "*.R$",
    full.names = TRUE, ignore.case = TRUE
)

sapply(save_predicitons_functions, source, .GlobalEnv)
```

```{r, warning=FALSE, message=FALSE}
# Connect to the SQLite database
con <- dbConnect(SQLite(), paste0(here(), "/data/footy-tipper-db.sqlite"))

# Query to select all records from the predictions_table
query <- "

    with min_round_id as (

        select min(round_id) as round_id
        from footy_tipping_data
        where game_state_name = 'Pre Game'

    )

    select ft.game_id
        , p.home_team_result
        , ft.team_home
        , ft.position_home
        , ft.team_head_to_head_odds_home
        , ft.team_away
        , ft.position_away
        , ft.team_head_to_head_odds_away
        , p.home_team_win_prob
        , p.home_team_lose_prob
        , ft.home_elo
        , ft.away_elo
        , ft.round_id
        , ft.competition_year
    from predictions_table p
    left join footy_tipping_data ft on p.game_id = ft.game_id
    where ft.game_state_name = 'Pre Game'
    and round_id = (select * from min_round_id)

"

# Execute the query and fetch the results into a data frame
predictions <- dbGetQuery(con, query)
predictions

# Disconnect from the SQLite database
dbDisconnect(con)
```

# Save them to the drive

```{r}
googledrive::drive_auth(
    path = paste0(here(), "/service-account-token.json"),
    scopes = "https://www.googleapis.com/auth/drive"
)

save_predictions(predictions, prod_run = prod_run)

levons_picks(predictions, prod_run = prod_run)
```
